### ISSUE TITLE
Unexpected error when starts game

### ISSUE THREAD

**Issue by kiritinhokirigaya** [osudroid/osu-droid#463]
### Issue description

- Expected result: What were you expecting to happen? Started the game, obviously
- Actual result: What actually happened? The game has a unexpected "error"

### Steps to reproduce the issue
1. Change the storage directory of the game
2. Open the game

#### Additional details / Screenshot / Clip
- Error details:
android.database.sqlite.SQLiteException: not an error (code 0): Could not open the database in read/write mode.
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:652)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:232)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:190)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.kt:632)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.kt:451)
	at com.reco1l.osu.data.IBeatmapInfoDAO_Impl.getBeatmapSetList(IBeatmapInfoDAO_Impl.java:293)
	at ru.nsu.ccfit.zuev.osu.LibraryManager.loadLibrary(LibraryManager.java:78)
	at ru.nsu.ccfit.zuev.osu.MainActivity.loadBeatmapLibrary(MainActivity.java:471)
	at ru.nsu.ccfit.zuev.osu.MainActivity.lambda$onLoadComplete$2(MainActivity.java:303)
	at ru.nsu.ccfit.zuev.osu.MainActivity.$r8$lambda$-_IWxgnM0FoKo9bZuHZm9nc77qI(MainActivity.java)
	at ru.nsu.ccfit.zuev.osu.MainActivity$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
	at com.reco1l.osu.Execution.async$lambda$0(ExecutionOverloads.kt:24)
	at com.reco1l.osu.Execution.$r8$lambda$FU5eGVDz2ojaFVDAlK-lPlNXRBU(ExecutionOverloads.kt)
	at com.reco1l.osu.Execution$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass)
	at com.reco1l.toolkt.kotlin.ExecutionKt$async$1.invokeSuspend(Execution.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1762f13, Dispatchers.Default]

### Versions
* Android version: Android 7.0
* Game version: 1.8 Patch 4

### Crashdump, backtrace or other files
Nothing here

**Comment by Rian8337** [comment]
Please ensure that you are moving the directory to a place that the game has read and write access to.

**Comment by kiritinhokirigaya** [comment]
But i allowed the directory access to the game read-and-write archives. What is happening?

**Comment by Reco1I** [comment]
> But i allowed the directory access to the game read-and-write archives. What is happening?

Have you changed main directory location in game settings?

**Comment by kiritinhokirigaya** [comment]
yes

> > But i allowed the directory access to the game read-and-write archives. What is happening?
> 
> Have you changed main directory location in game settings?

yes

**Comment by kiritinhokirigaya** [comment]
hmm, i will try

**Comment by kiritinhokirigaya** [comment]
GOOD, I TRYED, but now has other error:
java.lang.IllegalStateException: Fragment SettingsFragment{34a821c} (8fe349cc-ce3e-4bca-8c7d-e6b5b4aba652) not attached to an activity.
	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:928)
	at com.reco1l.osu.ui.SettingsFragment.handleAdvancedSectionPreferences$lambda$23(SettingsFragment.kt:355)
	at com.reco1l.osu.ui.SettingsFragment.$r8$lambda$KsK7ZPz9MBUVnSn8grQjlng6unw(SettingsFragment.kt)
	at com.reco1l.osu.ui.SettingsFragment$$ExternalSyntheticLambda11.onPreferenceChange(D8$$SyntheticClass)
	at com.reco1l.osu.ui.InputPreference.onValueChange(Preference.kt:227)
	at com.reco1l.osu.ui.InputPreference.setText$lambda$1(Preference.kt:202)
	at com.reco1l.osu.ui.InputPreference.$r8$lambda$_G449UsHfNKI8n0h0DGpiOYM94c(Preference.kt)
	at com.reco1l.osu.ui.InputPreference$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:755)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
	
	When i click to restart the game, only appears a black screen and the game wont load

**Comment by Reco1I** [comment]
Don't change the main directory.

**Comment by kiritinhokirigaya** [comment]
wait. wait a moment... Will it be that if I just change the beatmaps directory, the game won't crash?

**Comment by Reco1I** [comment]
> wait. wait a moment... Will it be that if I just change the beatmaps directory, the game won't crash?

Certainly, that's because you're trying to set a directory that the game is not allowed to write on.

**Comment by kiritinhokirigaya** [comment]
hmmmm....

**Comment by Rian8337** [comment]
That depends on whether the game is **allowed to write** to the directory. The same goes for the main directory.

**Comment by kiritinhokirigaya** [comment]
AND, i was correct, the game wont crashed changing only the beatmaps directory

**Comment by kiritinhokirigaya** [comment]
thanks guys for helping me with this. Bye!
