### ISSUE TITLE
Crash when back from mod menu if no song is selceted

### ISSUE THREAD

**Issue by EdrowsLuo** [osudroid/osu-droid#64]
If there are not  songs selected when back from mod menu, DifficultyReCalculator throws a NullPointerException and crash.

Found by: Badplayer101  
Video: https://youtu.be/s8MiAw5Kwyc  

StackTrace as below:
```
2020-12-27 22:40:28.929 32133-6029/ru.nsu.ccfit.zuev.osuplus.debug E/AndroidRuntime: FATAL EXCEPTION: Thread-19
    Process: ru.nsu.ccfit.zuev.osuplus.debug, PID: 32133
    java.lang.NullPointerException: Attempt to invoke virtual method 'float ru.nsu.ccfit.zuev.osu.TrackInfo.getCircleSize()' on a null object reference
        at ru.nsu.ccfit.zuev.osu.helper.DifficultyReCalculator.getCS(DifficultyReCalculator.java:388)
        at ru.nsu.ccfit.zuev.osu.helper.DifficultyReCalculator.getCS(DifficultyReCalculator.java:407)
        at ru.nsu.ccfit.zuev.osu.menu.ModMenu$2$1.run(ModMenu.java:174)
```

**Comment by EdrowsLuo** [comment]
@None1637
